export const INITIAL_ROUTE='/'
export const LOGIN_ROUTE='/login'
export const ADMIN_LOGIN_ROUTE='/admin/login'
export const TRANSACTION_ROUTE='/transaction'
export const ERROR_PAGE_MSG="The page Is Not found Enter Valid URL"
export const QUERY_KEY="transaction"
export const LOCAL_TOKEN="token"
export const LOCAL_ADMIN='admin'
export const LOGIN_ERROR="Please Enter Valid Details"
export const FAIL_ERROR="Fail to Fetch Data"
export const ROLE="user"
export const CONTENT_TYPE="application/json"
export const SECRETE_KEY="g08A3qQy00y8yFDq3y6N1ZQnhOPOa4msdie5EtKS1hFStar01JzPKrtKEzYY2BtF"
export const ALL_TRANSACTION_API= "https://bursting-gelding-24.hasura.app/api/rest/all-transactions"
export const TOTAL_TRANSACTION_API= 'https://bursting-gelding-24.hasura.app/api/rest/credit-debit-totals'
export const DELETE_TRANSACTION_API="https://bursting-gelding-24.hasura.app/api/rest/delete-transaction?id="
export const ADD_TRANSACTION_API="https://bursting-gelding-24.hasura.app/api/rest/add-transaction"
export const UPDATE_TRANSACTION_API='https://bursting-gelding-24.hasura.app/api/rest/update-transaction'
export const LOGIN_API="https://bursting-gelding-24.hasura.app/api/rest/get-user-id"
export const PROFILE_API='https://bursting-gelding-24.hasura.app/api/rest/profile'