export const InitialRoute='/'
export const LoginRoute='/login'
export const AdminLoginRoute='/admin/login'
export const TransactionRoute='/transaction'
export const ErrorPageMessage="The page Is Not found Enter Valid url"
export const QueryKey="transaction"
export const LocalToken="token"
export const LocalUserDetails='userDetails'
export const LocalAdmin='admin'
export const LoginError="Please Enter Valid Details"
export const FailError="Fail to Fetch Data"
export const Role="user"
export const ContentType="application/json"
export const Secret="g08A3qQy00y8yFDq3y6N1ZQnhOPOa4msdie5EtKS1hFStar01JzPKrtKEzYY2BtF"
export const AllTransactionApi= "https://bursting-gelding-24.hasura.app/api/rest/all-transactions"
export const TotalTransactionApi= 'https://bursting-gelding-24.hasura.app/api/rest/credit-debit-totals'
export const DeleteTransactionApi="https://bursting-gelding-24.hasura.app/api/rest/delete-transaction?id="
export const AddTransactionApi="https://bursting-gelding-24.hasura.app/api/rest/add-transaction"
export const UpdateTransactionApi='https://bursting-gelding-24.hasura.app/api/rest/update-transaction'
export const LoginApi="https://bursting-gelding-24.hasura.app/api/rest/get-user-id"